title: zzz
frequency: 1
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- templates
ext:
- go
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - go mod tidy
  after:
  - ./digbot scan -i 127.0.0.1
  - ./digbot web &
  exit:
  - echo "exit"
link: https://github.com/midoks/digbot
