title: zzz
frequency: 1
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- templates
ext:
- go
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - ps -ef|grep 'digbot web'| grep -v grep | awk '{print $2}' | xargs kill -9
  - go mod tidy
  after:
  - ./swag init
  - ./digbot scan -i 127.0.0.1
  - ./digbot web &
  exit:
  - ps -ef|grep 'digbot web'| grep -v grep | awk '{print $2}' | xargs kill -9
link: https://github.com/midoks/digbot
